<a href="https://colab.research.google.com/github/swordwalid/ML-Projects-/blob/main/Feature_extractor_PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Help (1)/Parkinson/pd_speech_features.csv')

In [ ]:
df.columns

Index(['id', 'gender', 'PPE', 'DFA', 'RPDE', 'numPulses', 'numPeriodsPulses',
       'meanPeriodPulses', 'stdDevPeriodPulses', 'locPctJitter',
       ...
       'tqwt_kurtosisValue_dec_28', 'tqwt_kurtosisValue_dec_29',
       'tqwt_kurtosisValue_dec_30', 'tqwt_kurtosisValue_dec_31',
       'tqwt_kurtosisValue_dec_32', 'tqwt_kurtosisValue_dec_33',
       'tqwt_kurtosisValue_dec_34', 'tqwt_kurtosisValue_dec_35',
       'tqwt_kurtosisValue_dec_36', 'class'],
      dtype='object', length=755)

In [ ]:
df.describe()

id      gender         PPE         DFA        RPDE   numPulses  \
count  756.000000  756.000000  756.000000  756.000000  756.000000  756.000000   
mean   125.500000    0.515873    0.746284    0.700414    0.489058  323.972222   
std     72.793721    0.500079    0.169294    0.069718    0.137442   99.219059   
min      0.000000    0.000000    0.041551    0.543500    0.154300    2.000000   
25%     62.750000    0.000000    0.762833    0.647053    0.386537  251.000000   
50%    125.500000    1.000000    0.809655    0.700525    0.484355  317.000000   
75%    188.250000    1.000000    0.834315    0.754985    0.586515  384.250000   
max    251.000000    1.000000    0.907660    0.852640    0.871230  907.000000   

       numPeriodsPulses  meanPeriodPulses  stdDevPeriodPulses  locPctJitter  \
count        756.000000        756.000000          756.000000    756.000000   
mean         322.678571          0.006360            0.000383      0.002324   
std           99.402499          0.001826            0.000728      0.002628   
min            1.000000          0.002107            0.000011      0.000210   
25%          250.000000          0.005003            0.000049      0.000970   
50%          316.000000          0.006048            0.000077      0.001495   
75%          383.250000          0.007528            0.000171      0.002520   
max          905.000000          0.012966            0.003483      0.027750   

       ...  tqwt_kurtosisValue_dec_28  tqwt_kurtosisValue_dec_29  \
count  ...                 756.000000                 756.000000   
mean   ...                  26.237251                  22.840337   
std    ...                  42.220693                  32.626464   
min    ...                   1.509800                   1.531700   
25%    ...                   2.408675                   3.452800   
50%    ...                   5.586300                   7.062750   
75%    ...                  28.958075                  29.830850   
max    ...                 239.788800                 203.311300   

       tqwt_kurtosisValue_dec_30  tqwt_kurtosisValue_dec_31  \
count                 756.000000                 756.000000   
mean                   18.587888                  13.872018   
std                    25.537464                  20.046029   
min                     1.582900                   1.747200   
25%                     3.354825                   3.077450   
50%                     6.077400                   4.770850   
75%                    21.944050                  13.188000   
max                   121.542900                 102.207000   

       tqwt_kurtosisValue_dec_32  tqwt_kurtosisValue_dec_33  \
count                 756.000000                 756.000000   
mean                   12.218953                  12.375335   
std                    17.783642                  16.341665   
min                     1.789500                   1.628700   
25%                     2.937025                   3.114375   
50%                     4.300450                   4.741450   
75%                    10.876150                  12.201325   
max                    85.571700                  73.532200   

       tqwt_kurtosisValue_dec_34  tqwt_kurtosisValue_dec_35  \
count                 756.000000                 756.000000   
mean                   14.799230                  14.751559   
std                    15.722502                  14.432979   
min                     1.861700                   1.955900   
25%                     3.665925                   3.741275   
50%                     6.725700                   7.334250   
75%                    21.922050                  22.495175   
max                    62.007300                  57.544300   

       tqwt_kurtosisValue_dec_36       class  
count                 756.000000  756.000000  
mean                   31.481110    0.746032  
std                    34.230991    0.435568  
min                     2.364000    0.000000  
25%                  

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Columns: 755 entries, id to class
dtypes: float64(749), int64(6)
memory usage: 4.4 MB


In [ ]:
df.shape

(756, 755)

In [ ]:
df['class'].value_counts()

1    564
0    192
Name: class, dtype: int64

In [ ]:
X=df.drop('class',axis=1)

In [ ]:
X.shape

(756, 754)

In [ ]:
y=df.iloc[:,-1]

In [ ]:
y

0      1
1      1
2      1
3      1
4      1
      ..
751    0
752    0
753    0
754    0
755    0
Name: class, Length: 756, dtype: int64

In [ ]:
import keras

In [ ]:
#keras.utils.all_utils.Sequence

In [ ]:
from imblearn.over_sampling import SMOTE
from collections import Counter
counter=Counter(y)
print('Before oversampling',counter)
sm=SMOTE()
x,y = sm.fit_resample(X,y)
counter=Counter(y)
print('After oversampling',counter)

Before oversampling Counter({1: 564, 0: 192})
After oversampling Counter({1: 564, 0: 564})


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train.shape,y_train.shape

((902, 754), (902,))

In [ ]:
x_test.shape,y_test.shape

((226, 754), (226,))

Principal Component Analysis

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=30)
x_train= pca.fit_transform(x_train)
x_test=pca.transform(x_test)

### Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

lr=LogisticRegression()
lr.fit(x_train,y_train)

predlr=lr.predict(x_test)

print(f"Accuracy of support vector  classifier is: {accuracy_score(y_test,predlr )}")

print(confusion_matrix(y_test, predlr))
print(classification_report(y_test, predlr))

Accuracy of support vector  classifier is: 0.6327433628318584
[[44 65]
 [18 99]]
              precision    recall  f1-score   support

           0       0.71      0.40      0.51       109
           1       0.60      0.85      0.70       117

    accuracy                           0.63       226
   macro avg       0.66      0.62      0.61       226
weighted avg       0.65      0.63      0.61       226



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [ ]:
#SVC

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
modelSVC = SVC()
modelSVC.fit(x_train, y_train)
#print(modelSVC.score(x_test, y_test))

y_pred = modelSVC.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.6902654867256637
[[61 48]
 [22 95]]
              precision    recall  f1-score   support

           0       0.73      0.56      0.64       109
           1       0.66      0.81      0.73       117

    accuracy                           0.69       226
   macro avg       0.70      0.69      0.68       226
weighted avg       0.70      0.69      0.68       226



### Decision Tree

In [ ]:
from sklearn import tree
from sklearn.metrics import accuracy_score

modelDTC = tree.DecisionTreeClassifier()
modelDTC.fit(x_train, y_train)
#print(modelDTC.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelDTC.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.7654867256637168
[[87 22]
 [31 86]]
              precision    recall  f1-score   support

           0       0.74      0.80      0.77       109
           1       0.80      0.74      0.76       117

    accuracy                           0.77       226
   macro avg       0.77      0.77      0.77       226
weighted avg       0.77      0.77      0.77       226



### Random Forest

In [ ]:
from sklearn import ensemble
from sklearn.metrics import accuracy_score

modelRFC = ensemble.RandomForestClassifier()
modelRFC.fit(x_train, y_train)
#print(modelRFC.score(x_test, y_test))


# Predicting the Test set results
y_pred = modelRFC.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.911504424778761
[[101   8]
 [ 12 105]]
              precision    recall  f1-score   support

           0       0.89      0.93      0.91       109
           1       0.93      0.90      0.91       117

    accuracy                           0.91       226
   macro avg       0.91      0.91      0.91       226
weighted avg       0.91      0.91      0.91       226



### Gaussian Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

modelGNB = GaussianNB()
modelGNB.fit(x_train, y_train)
#print(modelMNB.score(x_test, y_test))


# Predicting the Test set results
y_pred = modelGNB.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.5619469026548672
[[106   3]
 [ 96  21]]
              precision    recall  f1-score   support

           0       0.52      0.97      0.68       109
           1       0.88      0.18      0.30       117

    accuracy                           0.56       226
   macro avg       0.70      0.58      0.49       226
weighted avg       0.71      0.56      0.48       226



### KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

modelKNN = KNeighborsClassifier(n_neighbors = 5, weights = 'uniform', metric = 'minkowski', p = 2)
modelKNN.fit(x_train, y_train)
#print(modelKNN.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelKNN.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.672566371681416
[[73 36]
 [38 79]]
              precision    recall  f1-score   support

           0       0.66      0.67      0.66       109
           1       0.69      0.68      0.68       117

    accuracy                           0.67       226
   macro avg       0.67      0.67      0.67       226
weighted avg       0.67      0.67      0.67       226



### Gradiant Boosting

In [ ]:
modelGBC = ensemble.GradientBoostingClassifier(max_depth = 3)
modelGBC.fit(x_train, y_train)
#print(modelGBC.score(x_test_smt, y_test_smt))


# Predicting the Test set results
y_pred = modelGBC.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.8672566371681416
[[99 10]
 [20 97]]
              precision    recall  f1-score   support

           0       0.83      0.91      0.87       109
           1       0.91      0.83      0.87       117

    accuracy                           0.87       226
   macro avg       0.87      0.87      0.87       226
weighted avg       0.87      0.87      0.87       226



### AdaBoost

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

modelABC = AdaBoostClassifier(random_state = 96)
modelABC.fit(x_train, y_train)
#print(modelABC.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelABC.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.7477876106194691
[[77 32]
 [25 92]]
              precision    recall  f1-score   support

           0       0.75      0.71      0.73       109
           1       0.74      0.79      0.76       117

    accuracy                           0.75       226
   macro avg       0.75      0.75      0.75       226
weighted avg       0.75      0.75      0.75       226



### Stochastic Gradient Descent

In [ ]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
# loss = 'hinge'
modelSGDC = SGDClassifier()#loss = 'log', penalty = "l1", max_iter = 10
modelSGDC.fit(x_train, y_train)
#print(modelSGDC.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelSGDC.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.6902654867256637
[[65 44]
 [26 91]]
              precision    recall  f1-score   support

           0       0.71      0.60      0.65       109
           1       0.67      0.78      0.72       117

    accuracy                           0.69       226
   macro avg       0.69      0.69      0.69       226
weighted avg       0.69      0.69      0.69       226



#### XGBoost

In [ ]:
from xgboost import XGBClassifier
xg = XGBClassifier()
xg_fit=xg.fit(x_train, y_train)
predxg = xg_fit.predict(x_test)

print(f"Accuracy of support vector  classifier is: {accuracy_score(y_test,predxg )}")

print(confusion_matrix(y_test, predxg))
print(classification_report(y_test, predxg))

Accuracy of support vector  classifier is: 0.8451327433628318
[[94 15]
 [20 97]]
              precision    recall  f1-score   support

           0       0.82      0.86      0.84       109
           1       0.87      0.83      0.85       117

    accuracy                           0.85       226
   macro avg       0.85      0.85      0.85       226
weighted avg       0.85      0.85      0.85       226

