<a href="https://colab.research.google.com/github/swordwalid/ML-Projects-/blob/main/Feature_extractor_ICA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Help (1)/Parkinson/pd_speech_features.csv')

In [ ]:
df.columns

Index(['id', 'gender', 'PPE', 'DFA', 'RPDE', 'numPulses', 'numPeriodsPulses',
       'meanPeriodPulses', 'stdDevPeriodPulses', 'locPctJitter',
       ...
       'tqwt_kurtosisValue_dec_28', 'tqwt_kurtosisValue_dec_29',
       'tqwt_kurtosisValue_dec_30', 'tqwt_kurtosisValue_dec_31',
       'tqwt_kurtosisValue_dec_32', 'tqwt_kurtosisValue_dec_33',
       'tqwt_kurtosisValue_dec_34', 'tqwt_kurtosisValue_dec_35',
       'tqwt_kurtosisValue_dec_36', 'class'],
      dtype='object', length=755)

In [ ]:
df.describe()

id      gender         PPE         DFA        RPDE   numPulses  \
count  756.000000  756.000000  756.000000  756.000000  756.000000  756.000000   
mean   125.500000    0.515873    0.746284    0.700414    0.489058  323.972222   
std     72.793721    0.500079    0.169294    0.069718    0.137442   99.219059   
min      0.000000    0.000000    0.041551    0.543500    0.154300    2.000000   
25%     62.750000    0.000000    0.762833    0.647053    0.386537  251.000000   
50%    125.500000    1.000000    0.809655    0.700525    0.484355  317.000000   
75%    188.250000    1.000000    0.834315    0.754985    0.586515  384.250000   
max    251.000000    1.000000    0.907660    0.852640    0.871230  907.000000   

       numPeriodsPulses  meanPeriodPulses  stdDevPeriodPulses  locPctJitter  \
count        756.000000        756.000000          756.000000    756.000000   
mean         322.678571          0.006360            0.000383      0.002324   
std           99.402499          0.001826            0.000728      0.002628   
min            1.000000          0.002107            0.000011      0.000210   
25%          250.000000          0.005003            0.000049      0.000970   
50%          316.000000          0.006048            0.000077      0.001495   
75%          383.250000          0.007528            0.000171      0.002520   
max          905.000000          0.012966            0.003483      0.027750   

       ...  tqwt_kurtosisValue_dec_28  tqwt_kurtosisValue_dec_29  \
count  ...                 756.000000                 756.000000   
mean   ...                  26.237251                  22.840337   
std    ...                  42.220693                  32.626464   
min    ...                   1.509800                   1.531700   
25%    ...                   2.408675                   3.452800   
50%    ...                   5.586300                   7.062750   
75%    ...                  28.958075                  29.830850   
max    ...                 239.788800                 203.311300   

       tqwt_kurtosisValue_dec_30  tqwt_kurtosisValue_dec_31  \
count                 756.000000                 756.000000   
mean                   18.587888                  13.872018   
std                    25.537464                  20.046029   
min                     1.582900                   1.747200   
25%                     3.354825                   3.077450   
50%                     6.077400                   4.770850   
75%                    21.944050                  13.188000   
max                   121.542900                 102.207000   

       tqwt_kurtosisValue_dec_32  tqwt_kurtosisValue_dec_33  \
count                 756.000000                 756.000000   
mean                   12.218953                  12.375335   
std                    17.783642                  16.341665   
min                     1.789500                   1.628700   
25%                     2.937025                   3.114375   
50%                     4.300450                   4.741450   
75%                    10.876150                  12.201325   
max                    85.571700                  73.532200   

       tqwt_kurtosisValue_dec_34  tqwt_kurtosisValue_dec_35  \
count                 756.000000                 756.000000   
mean                   14.799230                  14.751559   
std                    15.722502                  14.432979   
min                     1.861700                   1.955900   
25%                     3.665925                   3.741275   
50%                     6.725700                   7.334250   
75%                    21.922050                  22.495175   
max                    62.007300                  57.544300   

       tqwt_kurtosisValue_dec_36       class  
count                 756.000000  756.000000  
mean                   31.481110    0.746032  
std                    34.230991    0.435568  
min                     2.364000    0.000000  
25%                  

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Columns: 755 entries, id to class
dtypes: float64(749), int64(6)
memory usage: 4.4 MB


In [ ]:
df.shape

(756, 755)

In [ ]:
df['class'].value_counts()

1    564
0    192
Name: class, dtype: int64

In [ ]:
X=df.drop('class',axis=1)

In [ ]:
X.shape

(756, 754)

In [ ]:
y=df.iloc[:,-1]

In [ ]:
y

0      1
1      1
2      1
3      1
4      1
      ..
751    0
752    0
753    0
754    0
755    0
Name: class, Length: 756, dtype: int64

In [ ]:
import keras

In [ ]:
#keras.utils.all_utils.Sequence

In [ ]:
# from imblearn.over_sampling import SMOTE
# from collections import Counter
# counter=Counter(y)
# print('Before oversampling',counter)
# sm=SMOTE()
# x,y = sm.fit_resample(X,y)
# counter=Counter(y)
# print('After oversampling',counter)

In [ ]:
from collections import Counter
from imblearn.combine import SMOTETomek
counter = Counter(y)
print('Before', counter)
smtt = SMOTETomek(random_state = 139)
x,y = smtt.fit_resample(X,y)
counter = Counter(y)
print('After', counter)

Before Counter({1: 564, 0: 192})
After Counter({1: 466, 0: 466})


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train.shape,y_train.shape

((745, 754), (745,))

In [ ]:
x_test.shape,y_test.shape

((187, 754), (187,))

Independent Component Analysis

In [ ]:
from sklearn.decomposition import FastICA
transformer = FastICA(n_components=50, random_state=8, max_iter=2000)

In [ ]:
transformer.fit(x_train)
x_train = transformer.transform(x_train)
x_test = transformer.transform(x_test)

### Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

lr=LogisticRegression()
lr.fit(x_train,y_train)

predlr=lr.predict(x_test)

print(f"Accuracy of support vector  classifier is: {accuracy_score(y_test,predlr )}")

print(confusion_matrix(y_test, predlr))
print(classification_report(y_test, predlr))

Accuracy of support vector  classifier is: 0.7807486631016043
[[73 27]
 [14 73]]
              precision    recall  f1-score   support

           0       0.84      0.73      0.78       100
           1       0.73      0.84      0.78        87

    accuracy                           0.78       187
   macro avg       0.78      0.78      0.78       187
weighted avg       0.79      0.78      0.78       187



In [ ]:
from sklearn.model_selection import cross_val_score
cv_score_for_LR = cross_val_score(lr, x_train, y_train, cv = 10)
cv_score_for_LR

array([0.82666667, 0.76      , 0.76      , 0.81333333, 0.77333333,
       0.74324324, 0.7972973 , 0.83783784, 0.78378378, 0.74324324])

In [ ]:
from statistics import mean
print('Accuracy mean and std : %.3f' % (mean(cv_score_for_LR)))

Accuracy mean and std : 0.784


In [ ]:
#SVC

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
modelSVC = SVC()
modelSVC.fit(x_train, y_train)
#print(modelSVC.score(x_test, y_test))

y_pred = modelSVC.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.8877005347593583
[[85 15]
 [ 6 81]]
              precision    recall  f1-score   support

           0       0.93      0.85      0.89       100
           1       0.84      0.93      0.89        87

    accuracy                           0.89       187
   macro avg       0.89      0.89      0.89       187
weighted avg       0.89      0.89      0.89       187



### Decision Tree

In [ ]:
from sklearn import tree
from sklearn.metrics import accuracy_score

modelDTC = tree.DecisionTreeClassifier()
modelDTC.fit(x_train, y_train)
#print(modelDTC.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelDTC.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.7967914438502673
[[78 22]
 [16 71]]
              precision    recall  f1-score   support

           0       0.83      0.78      0.80       100
           1       0.76      0.82      0.79        87

    accuracy                           0.80       187
   macro avg       0.80      0.80      0.80       187
weighted avg       0.80      0.80      0.80       187



### Random Forest

In [ ]:
from sklearn import ensemble
from sklearn.metrics import accuracy_score

modelRFC = ensemble.RandomForestClassifier()
modelRFC.fit(x_train, y_train)
#print(modelRFC.score(x_test, y_test))


# Predicting the Test set results
y_pred = modelRFC.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9251336898395722
[[87 13]
 [ 1 86]]
              precision    recall  f1-score   support

           0       0.99      0.87      0.93       100
           1       0.87      0.99      0.92        87

    accuracy                           0.93       187
   macro avg       0.93      0.93      0.93       187
weighted avg       0.93      0.93      0.93       187



### Gaussian Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

modelGNB = GaussianNB()
modelGNB.fit(x_train, y_train)
#print(modelMNB.score(x_test, y_test))


# Predicting the Test set results
y_pred = modelGNB.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.6684491978609626
[[94  6]
 [56 31]]
              precision    recall  f1-score   support

           0       0.63      0.94      0.75       100
           1       0.84      0.36      0.50        87

    accuracy                           0.67       187
   macro avg       0.73      0.65      0.63       187
weighted avg       0.72      0.67      0.63       187



### KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

modelKNN = KNeighborsClassifier(n_neighbors = 5, weights = 'uniform', metric = 'minkowski', p = 2)
modelKNN.fit(x_train, y_train)
#print(modelKNN.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelKNN.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.8716577540106952
[[96  4]
 [20 67]]
              precision    recall  f1-score   support

           0       0.83      0.96      0.89       100
           1       0.94      0.77      0.85        87

    accuracy                           0.87       187
   macro avg       0.89      0.87      0.87       187
weighted avg       0.88      0.87      0.87       187



### Gradiant Boosting

In [ ]:
modelGBC = ensemble.GradientBoostingClassifier(max_depth = 3)
modelGBC.fit(x_train, y_train)
#print(modelGBC.score(x_test_smt, y_test_smt))


# Predicting the Test set results
y_pred = modelGBC.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.8983957219251337
[[84 16]
 [ 3 84]]
              precision    recall  f1-score   support

           0       0.97      0.84      0.90       100
           1       0.84      0.97      0.90        87

    accuracy                           0.90       187
   macro avg       0.90      0.90      0.90       187
weighted avg       0.91      0.90      0.90       187



### AdaBoost

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

modelABC = AdaBoostClassifier(random_state = 96)
modelABC.fit(x_train, y_train)
#print(modelABC.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelABC.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.8288770053475936
[[77 23]
 [ 9 78]]
              precision    recall  f1-score   support

           0       0.90      0.77      0.83       100
           1       0.77      0.90      0.83        87

    accuracy                           0.83       187
   macro avg       0.83      0.83      0.83       187
weighted avg       0.84      0.83      0.83       187



### Stochastic Gradient Descent

In [ ]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
# loss = 'hinge'
modelSGDC = SGDClassifier()#loss = 'log', penalty = "l1", max_iter = 10
modelSGDC.fit(x_train, y_train)
#print(modelSGDC.score(x_test_smt, y_test_smt))

# Predicting the Test set results
y_pred = modelSGDC.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.786096256684492
[[80 20]
 [20 67]]
              precision    recall  f1-score   support

           0       0.80      0.80      0.80       100
           1       0.77      0.77      0.77        87

    accuracy                           0.79       187
   macro avg       0.79      0.79      0.79       187
weighted avg       0.79      0.79      0.79       187



#### XGBoost

In [ ]:
from xgboost import XGBClassifier
xg = XGBClassifier()
xg_fit=xg.fit(x_train, y_train)
predxg = xg_fit.predict(x_test)

print(f"Accuracy of support vector  classifier is: {accuracy_score(y_test,predxg )}")

print(confusion_matrix(y_test, predxg))
print(classification_report(y_test, predxg))

Accuracy of support vector  classifier is: 0.9197860962566845
[[87 13]
 [ 2 85]]
              precision    recall  f1-score   support

           0       0.98      0.87      0.92       100
           1       0.87      0.98      0.92        87

    accuracy                           0.92       187
   macro avg       0.92      0.92      0.92       187
weighted avg       0.93      0.92      0.92       187



In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import BaggingClassifier

estimators = [
         ('rf', RandomForestClassifier(n_estimators=100, random_state=42)),
         ('svc',SVC(random_state = 42)),
         ('xgb',XGBClassifier(n_estimators=100, random_state=42)),
         #('mlp', MLPClassifier()),
         #('abc', modelABC),
         #('lr', LogisticRegression(solver='liblinear'))
    ]
clf = StackingClassifier(
     #estimators=estimators, final_estimator = LogisticRegression(solver='liblinear')
     estimators=estimators, final_estimator = RandomForestClassifier(n_estimators=100, random_state=42)
     )


clf.fit(x_train, y_train).score(x_test, y_test)

# Predicting the Test set results
y_pred = clf.predict(x_test)
ac = accuracy_score(y_test, y_pred)
print(ac)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9090909090909091
[[87 13]
 [ 4 83]]
              precision    recall  f1-score   support

           0       0.96      0.87      0.91       100
           1       0.86      0.95      0.91        87

    accuracy                           0.91       187
   macro avg       0.91      0.91      0.91       187
weighted avg       0.91      0.91      0.91       187

